### PR TITLE
feat: detect conflict between dynamic routes and non dynamic ones

### LINKED ISSUE #658: fix: dynamic routes override non dynamic ones.
**Description**

When declaring a dynamic route, they will always take precedence over a non dynamic on. For example, imagine that I have the following route:

`GET /turtles/[id]`

And the following:

`POST /turtles/random`

When calling `curl -X POST http://localhost:8080/turtles/random`, `routes/turtles/[id]/index.dart` will be called instead of `routes/turtles/random.dart`, which can be confusing.

**Steps To Reproduce**

1. clone https://github.com/erickzanardo/ninja_turtles_api
2. start the server
3. `curl -X POST http://localhost:8080/turtles/random`
4. See the 405 error

**Expected Behavior**

I understand that this can be considered an expected behaviour, one could argue that `random` is simply an `id` that the `index.dart` inside the /turtles/[id]/` folder should consider and handle. Which I completely agree, but on the other hand, `random.dart` and `[id]/index.dart` files are conflicting routes.

I believe there are two possible ways of fixing this:
 - Non dynamic routes should take precedence over dynamic ones, so we could check for non dynamic route handlers before checking in dynamics ones, that way the example above would work. I believe this to be a preferred way of handling this, being able to split handlers like this can lead to a more organized route structure where we would be able to better split similar routes in different files.
 - Identify these conflicts and give a warning to the user

### PR DESCRIPTION
**Pull request by erickzanardo**
## Status

**READY**

## Description

This PR adds a validation to detect dynamic routes that would eventually "override" non dynamic ones and adds an error to notify the user, so that route issue don't go unnoticeable.

Ideally, we would try to order the routes in a way that the non dynamics ones would take precedence over the dynamic, but that proved a complicated implementation which would bring many other complications related to middlewares.

Since the user can still simply use a single dynamic route to both handle a `GET /pets/123` and a `GET /pets/mine`, we decided to go with marking routes as conflicted when we encounter such cases.

Example output:
Screenshot 2023-06-06 at 10 57 32

Fixes #658
Fixes: #631

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by felangel** [comment]
Why do we have output two conflicts per route pair?

**Comment by erickzanardo** [comment]
> Why do we have output two conflicts per route pair?

Since they conflict with each other. I couldn't think how to decide if we show `A -> B` or `B -> A`, so I thought we should just simply show both.

I am happy to remove the "duplication" if we can come with a good logic on how to decide on which of the order to show

**Comment by felangel** [comment]
> @felangel wdyt if we gave preference to the dynamic route, since it is the one that will handle most routes? Given a message like this:
> 
> ```
> both /turtles/random and /turtles/<id> resolve to /turtles/<id>
> ```
> 
> ?

Yup I think that makes sense and is what I expected when I originally saw the error.

**Review by wolfenrain — APPROVED** [review]

**Comment by erickzanardo** [comment]
@felangel here is the new output

Screenshot 2023-06-08 at 09 57 35

**Review by renancaraujo — APPROVED** [review]

**Pull request merged**
